### ISSUE TITLE
App Store

### ISSUE THREAD

**Issue by Jip-Hop** [mhaeuser/Custom-Search#1]
Will this be released on the iOS App Store? 😁

**Comment by mhaeuser** [comment]
Hey, it might be in the future (I don‘t care to pay Apple 99 € to release free software, but I know plenty of people with an account), but there are still some reports of Safari bugs.

With iOS Safari 16.0, the extension randomly stopped working for me every 2 - 4 days. While this was (apparently) fixed for me with 16.1, I got another report of this happening in a much worse fashion on a 16.1 device. Manifest v3 support in Safari is rather „new“ and I guess they need a few more point releases till it works nicely for everyone.

Once that happens, I‘ll look into this again. In the meantime, you can use AltStore to install the app and report whether there are any serious long-term issues. What I hit:
* In macOS 13.0 and iOS 16.{0,1}, you may rarely not be redirected to the configured search engine (once or twice every 1 - 2 days)
* In iOS 16.0 (and reportedly 16.1), the extension may randomly stop working and must be manually toggled off and on again (once every 2 - 4 days)
* In iOS 16.{0,1}, a blocked default search query may succeed if the browser is closed and re-started with it as active tab link

**Comment by Jip-Hop** [comment]
> I don‘t care to pay Apple 99 € to release free software

Understandable!

Using AltStore is not an option for me (needs to renew every 7 days) so I'll be looking forward to the day this shows up in the App store. 🙂

Great that you're working on customizing the Safari search engine by the way, a much needed feature IMHO.

**Comment by mhaeuser** [comment]
The first issue actually got much worse with macOS 13.1. Sigh.
